name = "cloud-mail-test"
main = "src/index.js"
compatibility_date = "2025-06-04"
keep_vars = true

[observability]
enabled = true
head_sampling_rate = 1

[[d1_databases]]
binding = "db"			#d1数据库绑定名默认不可修改
database_name = "cloud-mail"		#d1数据库名字
database_id = "608e5ae2-528d-4d87-af73-295f291f8c07"		#d1数据库id

[[kv_namespaces]]
binding = "kv"			#kv绑定名默认不可修改
id = "a4795b4ff8574555acbc454ee642bbef"					#kv数据库id

[[r2_buckets]]
binding = "r2"
bucket_name = "email-test"

[assets]
binding = "assets"
directory = "./dist"
not_found_handling = "single-page-application"
run_worker_first = true

[triggers]
crons = ["0 16 * * *"]

[vars]
orm_log = true
domain = ["coralera.org"]				#邮件域名可配置多个 示例: ["example1.com","example2.com"]
admin = "admin@coralera.org"				#管理员的邮箱	示例: admin@example.com
jwt_secret = "f27e412cd13dad36706321492a67367c"			#jwt令牌的密钥,随便填一串字符串
STORAGE_TYPE = "minio"		# 存储类型: "r2" 或 "minio"
# MinIO 配置 (当 STORAGE_TYPE = "minio" 时启用)
MINIO_ENDPOINT = "http://103.74.192.34:20075"	# MinIO 服务地址
MINIO_ACCESS_KEY = "minio"			# MinIO 访问密钥
MINIO_SECRET_KEY = "Mosary200064@."			# MinIO 密钥
MINIO_BUCKET_NAME = "attachment"		# MinIO 存储桶名称